### ISSUE TITLE
About how it works

### ISSUE THREAD

**Issue by Chen-YiDA** [aferaudo/user_policy_server#2]
Hello, I want to ask how to run this code?

**Comment by aferaudo** [comment]
Hi,
I'm sorry for my delay. I was a bit busy these weeks.

I saw that there was an error related to the multer package, I've just uploaded a newer version.

A part from that, I suppose that you have installed both openssl and mongodb.

Everything must be done in the folder "mudfs"

You need to create your certificate architecture in order to allow the server to properly work. I suggest you to follow the guide that I've indicated in the README file (I saw that the link was not working, I've changed it).

You should have the same file as showed in this [image](https://github.com/aferaudo/user_policy_server/blob/master/img/listcertificates.png)

Be sure that all these files are in a folder called "certs" and follow the nomenclature indicated in the image.

After that you can just run the command 
`npm start`

Depending on your settings, it could require to run the command as superuser. 

[link for useful openssl commands](https://techdocs.broadcom.com/content/broadcom/techdocs/us/en/ca-enterprise-software/it-operations-management/unified-infrastructure-management/9-0-2/upgrading/ca-uim-upgrade-step-3-deploy-the-upgrade/upgrade-uim-server/secure-hub-and-robot-ca-uim-9-sp1/Convert-Files-to-_pem-Format.html)
